id: I9E143DA9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T06:44:20+00:00'
last_modified: '2022-06-08T16:46:27.495414+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG17085
  title: དྲེལ་པའི་མི་ཚེ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    '5782':
      image_group_id: I1KG18470
      title: ''
      total_pages: 374
      order: 1
      base_file: 5782.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
